from __future__ import annotations

import base64
import io
import tempfile
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

import nibabel as nib
import numpy as np
import plotly.graph_objects as go
from dash import Dash, Input, Output, State, ctx, dcc, html
from dash.exceptions import PreventUpdate
from PIL import Image
from scipy.interpolate import RBFInterpolator
from scipy.ndimage import map_coordinates


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_FIXED_NIFTI = BASE_DIR / "img1.nii.gz"
DEFAULT_FIXED_IMAGE = BASE_DIR / "img1.png"
DEFAULT_MOVING_NPY = BASE_DIR / "img2.npy"
DEFAULT_MOVING_IMAGE = BASE_DIR / "img2.png"
OUTPUT_DIR = BASE_DIR / "registered_outputs"
Point = dict[str, float]
SourceInfo = dict[str, Any]
IMAGE_CACHE: dict[str, np.ndarray] = {}
AFFINE_CACHE: dict[str, np.ndarray] = {}
LANDMARK_COLORS = [
    "#ff2d55",
    "#007aff",
    "#34c759",
    "#ff9500",
    "#af52de",
    "#00c7be",
    "#ffcc00",
    "#5856d6",
    "#ff3b30",
    "#30b0c7",
]


def load_image(path: Path) -> np.ndarray:
    """Load an image from disk as an RGB uint8 array.

    Parameters:
        path: Image path to load.

    Returns:
        Image data with shape (height, width, 3).
    """
    with Image.open(path) as image:
        return np.asarray(image.convert("RGB"), dtype=np.uint8)


def load_nifti_volume(path: Path) -> np.ndarray:
    """Load a 3D NIfTI file as a floating point volume.

    Parameters:
        path: Path to a NIfTI image.

    Returns:
        NIfTI voxel data with shape (height, width, slices). For 4D data,
        the first trailing volume/channel is used.
    """
    nifti_image = nib.load(str(path))
    volume = np.asarray(nifti_image.get_fdata(dtype=np.float32))
    volume = np.squeeze(volume)

    while volume.ndim > 3:
        volume = volume[..., 0]
    if volume.ndim == 2:
        volume = volume[:, :, np.newaxis]
    if volume.ndim != 3:
        raise ValueError(f"Expected a 3D NIfTI volume, got shape {volume.shape}.")

    return volume


def load_nifti_volume_and_affine(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Load NIfTI voxel data and affine metadata.

    Parameters:
        path: Path to a NIfTI image.

    Returns:
        Tuple containing the scalar volume and affine matrix.
    """
    nifti_image = nib.load(str(path))
    return load_nifti_volume(path), np.asarray(nifti_image.affine, dtype=float)


def cache_image(image: np.ndarray) -> str:
    """Store image data in the server cache and return its lookup key.

    Parameters:
        image: Image or volume array to cache.

    Returns:
        Unique key for retrieving the cached image data.
    """
    key = str(uuid.uuid4())
    IMAGE_CACHE[key] = image
    return key


def cache_affine(affine: np.ndarray) -> str:
    """Store affine metadata in the server cache.

    Parameters:
        affine: NIfTI affine matrix.

    Returns:
        Unique key for retrieving the affine.
    """
    key = str(uuid.uuid4())
    AFFINE_CACHE[key] = np.asarray(affine, dtype=float)
    return key


def cached_image(key: str) -> np.ndarray:
    """Retrieve image data from the server cache.

    Parameters:
        key: Cache key generated by cache_image.

    Returns:
        Cached image or volume array.
    """
    return IMAGE_CACHE[key]


def cached_affine(key: str) -> np.ndarray:
    """Retrieve affine metadata from the server cache.

    Parameters:
        key: Cache key generated by cache_affine.

    Returns:
        Cached affine matrix.
    """
    return AFFINE_CACHE[key]


def rotate_clockwise(image: np.ndarray) -> np.ndarray:
    """Rotate an image or volume 90 degrees clockwise in the display plane.

    Parameters:
        image: Image array with at least two spatial dimensions.

    Returns:
        Rotated image array.
    """
    return np.rot90(image, k=-1, axes=(0, 1)).copy()


def flip_horizontal(image: np.ndarray) -> np.ndarray:
    """Flip an image or volume horizontally in the display plane.

    Parameters:
        image: Image array with at least two spatial dimensions.

    Returns:
        Horizontally flipped image array.
    """
    return np.flip(image, axis=1).copy()


def rotated_affine_clockwise(affine: np.ndarray, old_shape: tuple[int, int]) -> np.ndarray:
    """Update an affine after a clockwise display-plane rotation.

    Parameters:
        affine: Current voxel-to-world affine.
        old_shape: Previous image shape as height and width.

    Returns:
        Affine mapping rotated voxel coordinates to the same world space.
    """
    old_height, _ = old_shape
    transform = np.asarray(
        [
            [0.0, -1.0, 0.0, old_height - 1.0],
            [1.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ]
    )
    return affine @ transform


def flipped_affine_horizontal(affine: np.ndarray, old_shape: tuple[int, int]) -> np.ndarray:
    """Update an affine after a horizontal display-plane flip.

    Parameters:
        affine: Current voxel-to-world affine.
        old_shape: Previous image shape as height and width.

    Returns:
        Affine mapping flipped voxel coordinates to the same world space.
    """
    _, old_width = old_shape
    transform = np.asarray(
        [
            [1.0, 0.0, 0.0, 0.0],
            [0.0, -1.0, 0.0, old_width - 1.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ]
    )
    return affine @ transform


def array_to_scalar_image(array: np.ndarray) -> np.ndarray:
    """Convert an array into a 2D scalar image for registration.

    Parameters:
        array: Input array from NPY or image data.

    Returns:
        2D floating point scalar image.
    """
    image = np.asarray(array)
    if image.ndim == 3 and image.shape[-1] in {3, 4}:
        rgb_image = image[:, :, :3].astype(np.float32)
        scalar_image = np.mean(rgb_image, axis=2)
        white_mask = np.all(rgb_image >= 250.0, axis=2)
        scalar_image[white_mask] = np.nan
        return scalar_image.astype(np.float32)

    image = np.squeeze(image)
    if image.ndim == 2:
        return image.astype(np.float32)
    if image.ndim == 3:
        return image[:, :, image.shape[2] // 2].astype(np.float32)
    raise ValueError(f"Cannot convert array with shape {image.shape} to 2D scalar data.")


def array_to_rgb_image(array: np.ndarray) -> np.ndarray:
    """Convert a NumPy array into a displayable RGB image.

    Parameters:
        array: Input image array from a NumPy file.

    Returns:
        RGB uint8 image with shape (height, width, 3).
    """
    image = np.asarray(array)
    image = np.squeeze(image)

    if image.ndim == 2:
        return scalar_to_red_blue_rgb(image.astype(float))

    if image.ndim == 3 and image.shape[-1] in {3, 4}:
        rgb_image = image[:, :, :3]
        if rgb_image.dtype == np.uint8:
            return rgb_image

        finite_values = rgb_image[np.isfinite(rgb_image)]
        if finite_values.size == 0:
            return np.zeros((*rgb_image.shape[:2], 3), dtype=np.uint8)

        minimum = float(np.min(finite_values))
        maximum = float(np.max(finite_values))
        if maximum <= 1.0 and minimum >= 0.0:
            scaled = rgb_image * 255.0
        elif np.isclose(minimum, maximum):
            scaled = np.zeros_like(rgb_image, dtype=float)
        else:
            scaled = 255.0 * (rgb_image - minimum) / (maximum - minimum)
        return np.clip(scaled, 0, 255).astype(np.uint8)

    if image.ndim == 3:
        middle_slice = image[:, :, image.shape[2] // 2]
        return scalar_to_red_blue_rgb(middle_slice.astype(float))

    raise ValueError(f"Cannot display NumPy array with shape {image.shape}.")


def load_npy_image(path: Path) -> np.ndarray:
    """Load a NumPy image file as RGB data.

    Parameters:
        path: Path to a NumPy .npy file.

    Returns:
        RGB uint8 image.
    """
    return array_to_rgb_image(np.load(path))


def npy_data_uri_to_image(data_uri: str) -> np.ndarray:
    """Decode an uploaded NumPy .npy data URI into RGB image data.

    Parameters:
        data_uri: Uploaded NumPy file data URI.

    Returns:
        RGB uint8 image.
    """
    _, encoded = data_uri.split(",", maxsplit=1)
    raw = base64.b64decode(encoded)
    with io.BytesIO(raw) as buffer:
        array = np.load(buffer)
    return array_to_rgb_image(array)


def default_moving_image_data_uri() -> str:
    """Load the preferred default moving image source.

    Parameters:
        None.

    Returns:
        Base64 PNG data URI for the moving image display.
    """
    if DEFAULT_MOVING_NPY.exists():
        return image_to_data_uri(load_npy_image(DEFAULT_MOVING_NPY))

    return default_image_data_uri(DEFAULT_MOVING_IMAGE)


def make_moving_source_info(image: np.ndarray, name: str, kind: str) -> SourceInfo:
    """Create cache metadata for the PC3 source.

    Parameters:
        image: PC3 scalar or RGB image data.
        name: Human-readable source name.
        kind: Source kind, either scalar or rgb.

    Returns:
        Metadata used by Dash callbacks.
    """
    return {
        "key": cache_image(image),
        "name": name,
        "kind": kind,
        "shape": [int(value) for value in image.shape],
    }


def initial_moving_source_info() -> SourceInfo:
    """Load the preferred default PC3 source.

    Parameters:
        None.

    Returns:
        Metadata for the default PC3 source.
    """
    if DEFAULT_MOVING_NPY.exists():
        scalar_image = array_to_scalar_image(np.load(DEFAULT_MOVING_NPY))
        return make_moving_source_info(scalar_image, DEFAULT_MOVING_NPY.name, "scalar")
    if DEFAULT_MOVING_IMAGE.exists():
        rgb_image = load_image(DEFAULT_MOVING_IMAGE)
        return make_moving_source_info(rgb_image, DEFAULT_MOVING_IMAGE.name, "rgb")

    placeholder = np.full((256, 256), np.nan, dtype=np.float32)
    return make_moving_source_info(placeholder, "placeholder PC3", "scalar")


def moving_source_display_image(source_info: SourceInfo) -> np.ndarray:
    """Create a display RGB image for the active PC3 source.

    Parameters:
        source_info: Metadata for the active PC3 source.

    Returns:
        RGB uint8 display image.
    """
    image = cached_image(str(source_info["key"]))
    if source_info["kind"] == "scalar":
        return scalar_to_red_blue_rgb(image.astype(float))
    return image.astype(np.uint8)


def uploaded_moving_source_info(contents: str, filename: str | None) -> SourceInfo:
    """Decode an uploaded PC3 source from NPY or standard image formats.

    Parameters:
        contents: Uploaded file data URI.
        filename: Uploaded filename used to infer file type.

    Returns:
        Metadata for the uploaded PC3 source.
    """
    display_name = filename or "uploaded PC3"
    if filename and filename.endswith(".npy"):
        _, encoded = contents.split(",", maxsplit=1)
        raw = base64.b64decode(encoded)
        with io.BytesIO(raw) as buffer:
            scalar_image = array_to_scalar_image(np.load(buffer))
        return make_moving_source_info(scalar_image, display_name, "scalar")

    rgb_image = data_uri_to_image(contents)
    return make_moving_source_info(rgb_image, display_name, "rgb")


def transformed_moving_source_info(source_info: SourceInfo, transform: str) -> SourceInfo:
    """Apply a display-plane transform to the PC3 source.

    Parameters:
        source_info: Metadata for the active PC3 source.
        transform: Transform name, either rotate or flip.

    Returns:
        Metadata for the transformed PC3 source.
    """
    image = cached_image(str(source_info["key"]))
    if transform == "rotate":
        transformed = rotate_clockwise(image)
    elif transform == "flip":
        transformed = flip_horizontal(image)
    else:
        raise ValueError(f"Unsupported PC3 transform: {transform}")
    return make_moving_source_info(
        transformed,
        str(source_info["name"]),
        str(source_info["kind"]),
    )


def uploaded_moving_image_data_uri(contents: str, filename: str | None) -> str:
    """Decode an uploaded moving image from NPY or standard image formats.

    Parameters:
        contents: Uploaded file data URI.
        filename: Uploaded filename used to infer file type.

    Returns:
        Base64 PNG data URI for the moving image display.
    """
    if filename and filename.endswith(".npy"):
        return image_to_data_uri(npy_data_uri_to_image(contents))

    return contents


def rotated_fixed_source_info(
    source_info: SourceInfo,
    slice_index: int | None,
) -> SourceInfo:
    """Rotate the cached fixed source and return updated metadata.

    Parameters:
        source_info: Metadata for the active fixed image or volume.
        slice_index: Current fixed slice index to preserve.

    Returns:
        Metadata for the rotated fixed image or volume.
    """
    current_image = cached_image(str(source_info["key"]))
    rotated_image = rotate_clockwise(current_image)
    affine = None
    if "affine_key" in source_info:
        affine = rotated_affine_clockwise(
            cached_affine(str(source_info["affine_key"])),
            current_image.shape[:2],
        )
    updated_info = make_fixed_source_info(
        rotated_image,
        str(source_info["name"]),
        str(source_info["kind"]),
        affine,
    )
    updated_info["slice_index"] = int(slice_index or source_info["slice_index"])
    return updated_info


def flipped_fixed_source_info(
    source_info: SourceInfo,
    slice_index: int | None,
) -> SourceInfo:
    """Flip the cached fixed source horizontally and return updated metadata.

    Parameters:
        source_info: Metadata for the active fixed image or volume.
        slice_index: Current fixed slice index to preserve.

    Returns:
        Metadata for the flipped fixed image or volume.
    """
    current_image = cached_image(str(source_info["key"]))
    flipped_image = flip_horizontal(current_image)
    affine = None
    if "affine_key" in source_info:
        affine = flipped_affine_horizontal(
            cached_affine(str(source_info["affine_key"])),
            current_image.shape[:2],
        )
    updated_info = make_fixed_source_info(
        flipped_image,
        str(source_info["name"]),
        str(source_info["kind"]),
        affine,
    )
    updated_info["slice_index"] = int(slice_index or source_info["slice_index"])
    return updated_info


def normalize_slice_to_rgb(slice_data: np.ndarray) -> np.ndarray:
    """Convert a scalar 2D image slice into displayable RGB data.

    Parameters:
        slice_data: Scalar 2D image data.

    Returns:
        RGB uint8 image suitable for Plotly display.
    """
    finite_values = slice_data[np.isfinite(slice_data)]
    if finite_values.size == 0:
        normalized = np.zeros(slice_data.shape, dtype=np.uint8)
    else:
        low, high = np.percentile(finite_values, [1.0, 99.0])
        if np.isclose(low, high):
            low = float(np.min(finite_values))
            high = float(np.max(finite_values))
        if np.isclose(low, high):
            normalized = np.zeros(slice_data.shape, dtype=np.uint8)
        else:
            clipped = np.clip(slice_data, low, high)
            scaled = 255.0 * (clipped - low) / (high - low)
            scaled = np.nan_to_num(scaled, nan=0.0, posinf=255.0, neginf=0.0)
            normalized = np.clip(scaled, 0, 255).astype(np.uint8)

    return np.repeat(normalized[:, :, np.newaxis], 3, axis=2)


def normalize_scalar_image(slice_data: np.ndarray) -> np.ndarray:
    """Normalize a scalar image to the 0-to-1 display range.

    Parameters:
        slice_data: Scalar 2D image data.

    Returns:
        Floating point normalized image with values between 0 and 1.
    """
    finite_values = slice_data[np.isfinite(slice_data)]
    if finite_values.size == 0:
        return np.zeros(slice_data.shape, dtype=float)

    low, high = np.percentile(finite_values, [1.0, 99.0])
    if np.isclose(low, high):
        low = float(np.min(finite_values))
        high = float(np.max(finite_values))
    if np.isclose(low, high):
        return np.zeros(slice_data.shape, dtype=float)

    clipped = np.clip(slice_data, low, high)
    scaled = (clipped - low) / (high - low)
    scaled = np.nan_to_num(scaled, nan=0.0, posinf=1.0, neginf=0.0)
    return np.clip(scaled, 0.0, 1.0)


def scalar_to_red_blue_rgb(slice_data: np.ndarray) -> np.ndarray:
    """Convert a scalar PC3 image to a Matplotlib-like bwr RGB palette.

    Parameters:
        slice_data: Scalar 2D PC3 image data.

    Returns:
        RGB uint8 image using blue-white-red colors.
    """
    normalized = normalize_scalar_image(slice_data)
    red = np.minimum(1.0, 2.0 * normalized)
    green = np.where(normalized < 0.5, 2.0 * normalized, 2.0 * (1.0 - normalized))
    blue = np.minimum(1.0, 2.0 * (1.0 - normalized))
    rgb_image = np.stack([red, green, blue], axis=2)
    rgb_uint8 = np.clip(rgb_image * 255.0, 0, 255).astype(np.uint8)
    rgb_uint8[~np.isfinite(slice_data)] = [255, 255, 255]
    return rgb_uint8


def fixed_slice_image(source_info: SourceInfo, slice_index: int | None) -> np.ndarray:
    """Return the currently selected fixed image slice as RGB data.

    Parameters:
        source_info: Metadata for the cached fixed source.
        slice_index: Requested slice index for NIfTI data.

    Returns:
        RGB image displayed on the fixed side.
    """
    image = cached_image(str(source_info["key"]))
    if source_info["kind"] == "nifti":
        safe_index = int(slice_index or source_info["slice_index"])
        safe_index = max(0, min(safe_index, int(source_info["depth"]) - 1))
        return normalize_slice_to_rgb(image[:, :, safe_index])

    return image.astype(np.uint8)


def make_fixed_source_info(
    image: np.ndarray,
    name: str,
    kind: str,
    affine: np.ndarray | None = None,
) -> SourceInfo:
    """Create cache metadata for a fixed image source.

    Parameters:
        image: Fixed image or fixed volume data.
        name: Human-readable source name.
        kind: Source kind, either nifti or image.
        affine: Optional NIfTI affine matrix.

    Returns:
        Metadata used by Dash callbacks.
    """
    if kind == "nifti":
        depth = int(image.shape[2])
        slice_index = depth // 2
        shape = [int(image.shape[0]), int(image.shape[1]), depth]
    else:
        depth = 1
        slice_index = 0
        shape = [int(image.shape[0]), int(image.shape[1]), 1]

    source_info: SourceInfo = {
        "key": cache_image(image),
        "name": name,
        "kind": kind,
        "shape": shape,
        "depth": depth,
        "slice_index": slice_index,
    }
    if affine is not None:
        source_info["affine_key"] = cache_affine(affine)
    return source_info


def initial_fixed_source_info() -> SourceInfo:
    """Load the preferred default fixed image source.

    Parameters:
        None.

    Returns:
        Metadata for the default fixed NIfTI volume or PNG fallback.
    """
    if DEFAULT_FIXED_NIFTI.exists():
        volume, affine = load_nifti_volume_and_affine(DEFAULT_FIXED_NIFTI)
        return make_fixed_source_info(volume, DEFAULT_FIXED_NIFTI.name, "nifti", affine)

    image = load_image(DEFAULT_FIXED_IMAGE)
    return make_fixed_source_info(image, DEFAULT_FIXED_IMAGE.name, "image")


def uploaded_fixed_source_info(contents: str, filename: str | None) -> SourceInfo:
    """Decode an uploaded fixed image source.

    Parameters:
        contents: Uploaded file data URI.
        filename: Uploaded filename used to infer file type.

    Returns:
        Metadata for the uploaded fixed source.
    """
    display_name = filename or "uploaded fixed image"
    _, encoded = contents.split(",", maxsplit=1)
    raw = base64.b64decode(encoded)

    if display_name.endswith((".nii", ".nii.gz")):
        suffix = ".nii.gz" if display_name.endswith(".nii.gz") else ".nii"
        with tempfile.NamedTemporaryFile(suffix=suffix) as temporary_file:
            temporary_file.write(raw)
            temporary_file.flush()
            volume, affine = load_nifti_volume_and_affine(Path(temporary_file.name))
        return make_fixed_source_info(volume, display_name, "nifti", affine)

    with Image.open(io.BytesIO(raw)) as image:
        rgb_image = np.asarray(image.convert("RGB"), dtype=np.uint8)
    return make_fixed_source_info(rgb_image, display_name, "image")


def slice_slider_marks(depth: int) -> dict[int, str]:
    """Create sparse marks for the fixed-volume slice slider.

    Parameters:
        depth: Number of slices in the fixed volume.

    Returns:
        Dictionary of slider mark positions and labels.
    """
    if depth <= 1:
        return {0: "0"}

    raw_marks = {0, depth - 1, depth // 2}
    return {mark: str(mark) for mark in sorted(raw_marks)}


def image_to_data_uri(image: np.ndarray) -> str:
    """Encode an RGB image array as a PNG data URI.

    Parameters:
        image: Image data with shape (height, width, channels).

    Returns:
        Base64 PNG data URI suitable for Dash stores.
    """
    buffer = io.BytesIO()
    Image.fromarray(image.astype(np.uint8)).save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def data_uri_to_image(data_uri: str) -> np.ndarray:
    """Decode a Dash upload or stored data URI into an RGB image.

    Parameters:
        data_uri: Base64 encoded image data URI.

    Returns:
        Image data with shape (height, width, 3).
    """
    _, encoded = data_uri.split(",", maxsplit=1)
    raw = base64.b64decode(encoded)
    with Image.open(io.BytesIO(raw)) as image:
        return np.asarray(image.convert("RGB"), dtype=np.uint8)


def default_image_data_uri(path: Path) -> str:
    """Load a default image and encode it for client-side storage.

    Parameters:
        path: Default image path.

    Returns:
        Base64 PNG data URI for the image, or a placeholder if missing.
    """
    if not path.exists():
        placeholder = np.zeros((256, 256, 3), dtype=np.uint8)
        placeholder[:, :, 0] = 35
        placeholder[:, :, 1] = 45
        placeholder[:, :, 2] = 65
        return image_to_data_uri(placeholder)

    return image_to_data_uri(load_image(path))


def empty_figure(title: str, message: str | None = None) -> go.Figure:
    """Create an empty Plotly figure with an explanatory title.

    Parameters:
        title: Title to display above the empty figure.
        message: Optional message to show in the figure body.

    Returns:
        Plotly figure without image data.
    """
    figure = go.Figure()
    if message:
        figure.add_annotation(
            text=message,
            x=0.5,
            y=0.5,
            xref="paper",
            yref="paper",
            showarrow=False,
            font={"size": 18, "color": "#52606d"},
            align="center",
        )
    figure.update_layout(
        title=title,
        template="plotly_white",
        height=650,
        xaxis={"visible": False},
        yaxis={"visible": False},
        margin={"l": 20, "r": 20, "t": 45, "b": 20},
    )
    return figure


def image_figure(image: np.ndarray, points: list[Point], title: str) -> go.Figure:
    """Create an interactive image figure with landmark markers.

    Parameters:
        image: Image array to display.
        points: Landmark points in image coordinates.
        title: Figure title.

    Returns:
        Plotly figure containing the image and point annotations.
    """
    height, width = image.shape[:2]
    figure = go.Figure()
    figure.add_trace(go.Image(z=image))

    if points:
        x_values = [point["x"] for point in points]
        y_values = [point["y"] for point in points]
        labels = [str(index + 1) for index in range(len(points))]
        colors = [
            LANDMARK_COLORS[index % len(LANDMARK_COLORS)]
            for index in range(len(points))
        ]
        figure.add_trace(
            go.Scatter(
                x=x_values,
                y=y_values,
                text=labels,
                mode="markers+text",
                textposition="top center",
                textfont={"size": 18, "color": "white"},
                marker={
                    "size": 16,
                    "color": colors,
                    "opacity": 0.95,
                    "line": {"color": "black", "width": 2},
                },
                selected={"marker": {"opacity": 1.0}},
                unselected={"marker": {"opacity": 0.9}},
                name="Landmarks",
            )
        )

    figure.update_layout(
        title=title,
        clickmode="event+select",
        dragmode="pan",
        template="plotly_white",
        height=650,
        margin={"l": 20, "r": 20, "t": 45, "b": 20},
        uirevision=title,
    )
    figure.update_xaxes(range=[0, width], constrain="domain")
    figure.update_yaxes(range=[height, 0], scaleanchor="x", constrain="domain")
    return figure


def point_from_click(click_data: dict[str, Any] | None) -> Point:
    """Extract an image coordinate from Dash graph click data.

    Parameters:
        click_data: Dash clickData payload from a Plotly graph.

    Returns:
        Point dictionary containing x and y coordinates.
    """
    if not click_data or "points" not in click_data or not click_data["points"]:
        raise PreventUpdate

    point = click_data["points"][0]
    return {"x": float(point["x"]), "y": float(point["y"])}


def append_clicked_point(
    click_data: dict[str, Any] | None,
    points: list[Point] | None,
) -> list[Point]:
    """Append a clicked landmark to an existing point list.

    Parameters:
        click_data: Dash clickData payload from a Plotly graph.
        points: Existing landmark points.

    Returns:
        Updated landmark point list.
    """
    updated_points = list(points or [])
    updated_points.append(point_from_click(click_data))
    return updated_points


def undo_last_point(points: list[Point] | None) -> list[Point]:
    """Remove the most recently added landmark.

    Parameters:
        points: Existing landmark points.

    Returns:
        Point list without the final point.
    """
    updated_points = list(points or [])
    if updated_points:
        updated_points.pop()
    return updated_points


def landmarks_to_array(points: list[Point]) -> np.ndarray:
    """Convert point dictionaries to an Nx2 coordinate array.

    Parameters:
        points: Landmark points with x and y keys.

    Returns:
        Floating point coordinate array ordered as x, y.
    """
    return np.asarray([[point["x"], point["y"]] for point in points], dtype=float)


def boundary_landmarks(
    fixed_shape: tuple[int, int],
    moving_shape: tuple[int, int],
) -> tuple[np.ndarray, np.ndarray]:
    """Create boundary landmarks to stabilize extrapolation near image edges.

    Parameters:
        fixed_shape: Fixed image shape as height and width.
        moving_shape: Moving image shape as height and width.

    Returns:
        Pair of coordinate arrays for fixed-space and moving-space corners.
    """
    fixed_height, fixed_width = fixed_shape
    moving_height, moving_width = moving_shape
    fixed_points = np.asarray(
        [
            [0.0, 0.0],
            [fixed_width - 1.0, 0.0],
            [0.0, fixed_height - 1.0],
            [fixed_width - 1.0, fixed_height - 1.0],
        ],
        dtype=float,
    )
    moving_points = np.asarray(
        [
            [0.0, 0.0],
            [moving_width - 1.0, 0.0],
            [0.0, moving_height - 1.0],
            [moving_width - 1.0, moving_height - 1.0],
        ],
        dtype=float,
    )
    return fixed_points, moving_points


def warp_moving_to_fixed(
    moving_image: np.ndarray,
    fixed_shape: tuple[int, int],
    fixed_points: list[Point],
    moving_points: list[Point],
    stabilize_edges: bool,
    smoothing: float = 0.0,
) -> np.ndarray:
    """Warp the moving image into fixed-image coordinates using landmarks.

    Parameters:
        moving_image: RGB image that should be registered into fixed space.
        fixed_shape: Desired output shape as height and width.
        fixed_points: Landmarks selected in the fixed image.
        moving_points: Corresponding landmarks selected in the moving image.
        stabilize_edges: Whether to add image-corner constraints.
        smoothing: Thin-plate spline smoothing factor.

    Returns:
        Registered moving image with the fixed image shape.
    """
    target_points = landmarks_to_array(fixed_points)
    source_points = landmarks_to_array(moving_points)

    if stabilize_edges:
        fixed_boundary, moving_boundary = boundary_landmarks(
            fixed_shape=fixed_shape,
            moving_shape=moving_image.shape[:2],
        )
        target_points = np.vstack([target_points, fixed_boundary])
        source_points = np.vstack([source_points, moving_boundary])

    mapper = RBFInterpolator(
        target_points,
        source_points,
        kernel="thin_plate_spline",
        smoothing=smoothing,
    )

    fixed_height, fixed_width = fixed_shape
    grid_y, grid_x = np.mgrid[0:fixed_height, 0:fixed_width]
    target_grid = np.column_stack([grid_x.ravel(), grid_y.ravel()])
    source_grid = mapper(target_grid)

    source_x = source_grid[:, 0].reshape(fixed_height, fixed_width)
    source_y = source_grid[:, 1].reshape(fixed_height, fixed_width)
    registered = np.zeros((fixed_height, fixed_width, 3), dtype=np.float32)

    for channel in range(3):
        registered[:, :, channel] = map_coordinates(
            moving_image[:, :, channel],
            [source_y, source_x],
            order=1,
            mode="constant",
            cval=0.0,
        )

    registered = np.nan_to_num(registered, nan=0.0, posinf=255.0, neginf=0.0)
    return np.clip(registered, 0, 255).astype(np.uint8)


def fixed_to_moving_coordinate_grid(
    moving_shape: tuple[int, int],
    fixed_shape: tuple[int, int],
    fixed_points: list[Point],
    moving_points: list[Point],
    stabilize_edges: bool,
    smoothing: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Build source-coordinate grids from fixed-space landmarks.

    Parameters:
        moving_shape: Moving image shape as height and width.
        fixed_shape: Desired output shape as height and width.
        fixed_points: Landmarks selected in the fixed image.
        moving_points: Corresponding landmarks selected in the moving image.
        stabilize_edges: Whether to add image-corner constraints.
        smoothing: Thin-plate spline smoothing factor.

    Returns:
        Source y and x coordinate grids for resampling the moving image.
    """
    target_points = landmarks_to_array(fixed_points)
    source_points = landmarks_to_array(moving_points)

    if stabilize_edges:
        fixed_boundary, moving_boundary = boundary_landmarks(
            fixed_shape=fixed_shape,
            moving_shape=moving_shape,
        )
        target_points = np.vstack([target_points, fixed_boundary])
        source_points = np.vstack([source_points, moving_boundary])

    mapper = RBFInterpolator(
        target_points,
        source_points,
        kernel="thin_plate_spline",
        smoothing=smoothing,
    )
    fixed_height, fixed_width = fixed_shape
    grid_y, grid_x = np.mgrid[0:fixed_height, 0:fixed_width]
    target_grid = np.column_stack([grid_x.ravel(), grid_y.ravel()])
    source_grid = mapper(target_grid)
    source_x = source_grid[:, 0].reshape(fixed_height, fixed_width)
    source_y = source_grid[:, 1].reshape(fixed_height, fixed_width)
    return source_y, source_x


def warp_scalar_moving_to_fixed(
    moving_image: np.ndarray,
    fixed_shape: tuple[int, int],
    fixed_points: list[Point],
    moving_points: list[Point],
    stabilize_edges: bool,
    smoothing: float = 0.0,
) -> np.ndarray:
    """Warp scalar PC3 values into MRI slice coordinates.

    Parameters:
        moving_image: Scalar PC3 image to register.
        fixed_shape: Desired output shape as height and width.
        fixed_points: Landmarks selected in the MRI slice.
        moving_points: Corresponding landmarks selected in PC3.
        stabilize_edges: Whether to add image-corner constraints.
        smoothing: Thin-plate spline smoothing factor.

    Returns:
        Registered scalar PC3 image in MRI slice coordinates.
    """
    source_y, source_x = fixed_to_moving_coordinate_grid(
        moving_shape=moving_image.shape[:2],
        fixed_shape=fixed_shape,
        fixed_points=fixed_points,
        moving_points=moving_points,
        stabilize_edges=stabilize_edges,
        smoothing=smoothing,
    )
    registered = map_coordinates(
        moving_image.astype(np.float32),
        [source_y, source_x],
        order=1,
        mode="constant",
        cval=np.nan,
    )
    return registered.astype(np.float32)


def blend_images(fixed_image: np.ndarray, registered_image: np.ndarray) -> np.ndarray:
    """Blend fixed and registered images for visual quality control.

    Parameters:
        fixed_image: Reference image.
        registered_image: Moving image after registration.

    Returns:
        RGB overlay image.
    """
    blended = 0.5 * fixed_image.astype(float) + 0.5 * registered_image.astype(float)
    return np.clip(blended, 0, 255).astype(np.uint8)


def save_registered_image(image: np.ndarray, slice_index: int | None) -> Path:
    """Save a registered 2D image to the output directory.

    Parameters:
        image: Registered RGB image in fixed-slice pixel space.
        slice_index: Fixed-volume slice index used during registration.

    Returns:
        Path to the saved PNG image.
    """
    OUTPUT_DIR.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_slice = int(slice_index or 0)
    output_path = OUTPUT_DIR / f"registered_pc3_slice_{safe_slice:03d}_{timestamp}.png"
    Image.fromarray(image.astype(np.uint8)).save(output_path)
    return output_path


def selected_slice_affine(affine: np.ndarray, slice_index: int | None) -> np.ndarray:
    """Create a 2D NIfTI affine located at the selected MRI slice.

    Parameters:
        affine: MRI voxel-to-world affine.
        slice_index: Selected MRI slice index.

    Returns:
        Affine whose origin is shifted to the selected slice location.
    """
    safe_slice = int(slice_index or 0)
    output_affine = np.asarray(affine, dtype=float).copy()
    slice_origin = affine @ np.asarray([0.0, 0.0, float(safe_slice), 1.0])
    output_affine[:3, 3] = slice_origin[:3]
    return output_affine


def save_registered_nifti_slice(
    scalar_image: np.ndarray,
    fixed_source_info: SourceInfo,
    slice_index: int | None,
) -> Path:
    """Save registered PC3 as a 2D NIfTI in MRI world coordinates.

    Parameters:
        scalar_image: Registered scalar PC3 image in MRI slice pixel space.
        fixed_source_info: Metadata for the active MRI source.
        slice_index: Selected MRI slice index.

    Returns:
        Path to the saved NIfTI file.
    """
    if "affine_key" not in fixed_source_info:
        raise ValueError("The active MRI source does not have NIfTI affine metadata.")

    OUTPUT_DIR.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_slice = int(slice_index or 0)
    output_path = OUTPUT_DIR / f"registered_pc3_slice_{safe_slice:03d}_{timestamp}.nii.gz"
    affine = selected_slice_affine(
        cached_affine(str(fixed_source_info["affine_key"])),
        slice_index,
    )
    nifti_image = nib.Nifti1Image(scalar_image.astype(np.float32), affine)
    nifti_image.header.set_xyzt_units("mm")
    nib.save(nifti_image, str(output_path))
    return output_path


def points_summary(fixed_points: list[Point], moving_points: list[Point]) -> list[Any]:
    """Build a compact point-pair summary for the interface.

    Parameters:
        fixed_points: Landmarks selected in the fixed image.
        moving_points: Landmarks selected in the moving image.

    Returns:
        Dash HTML children describing point-pair status.
    """
    pair_count = min(len(fixed_points), len(moving_points))
    children: list[Any] = [
        html.P(
            f"{pair_count} complete pairs. "
            f"MRI: {len(fixed_points)} point(s), PC3: {len(moving_points)} point(s)."
        )
    ]

    if pair_count:
        rows = []
        for index in range(pair_count):
            fixed_point = fixed_points[index]
            moving_point = moving_points[index]
            rows.append(
                html.Tr(
                    [
                        html.Td(str(index + 1)),
                        html.Td(f"({fixed_point['x']:.1f}, {fixed_point['y']:.1f})"),
                        html.Td(f"({moving_point['x']:.1f}, {moving_point['y']:.1f})"),
                    ]
                )
            )
        children.append(
            html.Table(
                [
                    html.Thead(
                        html.Tr(
                            [
                                html.Th("#"),
                                html.Th("MRI"),
                                html.Th("PC3"),
                            ]
                        )
                    ),
                    html.Tbody(rows),
                ],
                className="point-table",
            )
        )

    return children


def app_layout() -> html.Div:
    """Create the Dash application layout.

    Parameters:
        None.

    Returns:
        Root Dash HTML component.
    """
    fixed_source = initial_fixed_source_info()
    moving_source = initial_moving_source_info()
    return html.Div(
        [
            dcc.Store(
                id="fixed-source-store",
                data=fixed_source,
            ),
            dcc.Store(
                id="moving-source-store",
                data=moving_source,
            ),
            dcc.Store(id="fixed-points-store", data=[]),
            dcc.Store(id="moving-points-store", data=[]),
            dcc.Store(id="registered-result-store", data=None),
            html.H1("Semi-Automatic Non-Rigid Registration"),
            html.P(
                "Click corresponding landmarks in the same order. "
                "The PC3 image is warped into the selected MRI slice."
            ),
            html.Div(
                [
                    html.Div(
                        [
                            html.H3("MRI: img1 NIfTI slice"),
                            dcc.Upload(
                                id="fixed-upload",
                                children=html.Div(
                                    ["Drag/drop or click to upload an MRI NIfTI/image"]
                                ),
                                multiple=False,
                                className="upload",
                            ),
                            html.Div(id="fixed-source-status", className="status"),
                            html.Label("Slice", htmlFor="fixed-slice-slider"),
                            dcc.Slider(
                                id="fixed-slice-slider",
                                min=0,
                                max=int(fixed_source["depth"]) - 1,
                                step=1,
                                value=int(fixed_source["slice_index"]),
                                marks=slice_slider_marks(int(fixed_source["depth"])),
                                disabled=int(fixed_source["depth"]) <= 1,
                            ),
                            dcc.Graph(id="fixed-graph", config={"scrollZoom": True}),
                            html.Button("Undo MRI point", id="undo-fixed"),
                            html.Button(
                                "Rotate MRI 90 deg clockwise",
                                id="rotate-fixed",
                            ),
                            html.Button(
                                "Flip MRI horizontally",
                                id="flip-fixed",
                            ),
                        ],
                        className="panel",
                    ),
                    html.Div(
                        [
                            html.H3("PC3: img2 NPY"),
                            dcc.Upload(
                                id="moving-upload",
                                children=html.Div(
                                    ["Drag/drop or click to upload a PC3 NPY/image"]
                                ),
                                multiple=False,
                                className="upload",
                            ),
                            dcc.Graph(id="moving-graph", config={"scrollZoom": True}),
                            html.Button("Undo PC3 point", id="undo-moving"),
                            html.Button(
                                "Rotate PC3 90 deg clockwise",
                                id="rotate-moving",
                            ),
                            html.Button(
                                "Flip PC3 horizontally",
                                id="flip-moving",
                            ),
                        ],
                        className="panel",
                    ),
                ],
                className="image-grid",
            ),
            html.Div(
                [
                    html.Button("Reset all points", id="reset-points"),
                    html.Button("Run registration", id="run-registration"),
                    html.Button("Save registered PC3 2D NIfTI", id="save-registered"),
                    dcc.Checklist(
                        id="stabilize-edges",
                        options=[
                            {
                                "label": "Stabilize edges with image corners",
                                "value": "stabilize",
                            }
                        ],
                        value=["stabilize"],
                    ),
                ],
                className="controls",
            ),
            html.Div(id="points-summary", className="summary"),
            html.Div(id="registration-status", className="status"),
            html.Div(id="save-status", className="status"),
            html.Div(
                [
                    dcc.Graph(
                        id="registered-graph",
                        figure=empty_figure("Registered PC3 in MRI space"),
                        config={"scrollZoom": True},
                    ),
                    dcc.Graph(
                        id="overlay-graph",
                        figure=empty_figure("MRI/registered PC3 overlay"),
                        config={"scrollZoom": True},
                    ),
                ],
                className="image-grid",
            ),
        ],
        className="page",
    )


def register_callbacks(app: Dash) -> None:
    """Register Dash callbacks for image loading, landmarks, and registration.

    Parameters:
        app: Dash application instance.

    Returns:
        None.
    """

    @app.callback(
        Output("fixed-source-store", "data"),
        Input("fixed-upload", "contents"),
        Input("rotate-fixed", "n_clicks"),
        Input("flip-fixed", "n_clicks"),
        State("fixed-upload", "filename"),
        State("fixed-source-store", "data"),
        State("fixed-slice-slider", "value"),
        prevent_initial_call=True,
    )
    def update_fixed_image(
        contents: str | None,
        rotate_clicks: int | None,
        flip_clicks: int | None,
        filename: str | None,
        source_info: SourceInfo,
        slice_index: int | None,
    ) -> SourceInfo:
        """Update the fixed image store after an upload.

        Parameters:
            contents: Uploaded image data URI.
            rotate_clicks: Number of fixed-image rotation button clicks.
            flip_clicks: Number of fixed-image horizontal flip button clicks.
            filename: Uploaded filename.
            source_info: Metadata for the active fixed source.
            slice_index: Current fixed slice index.

        Returns:
            Metadata for the uploaded fixed image source.
        """
        if ctx.triggered_id == "rotate-fixed":
            if not rotate_clicks:
                raise PreventUpdate
            return rotated_fixed_source_info(source_info, slice_index)
        if ctx.triggered_id == "flip-fixed":
            if not flip_clicks:
                raise PreventUpdate
            return flipped_fixed_source_info(source_info, slice_index)
        if ctx.triggered_id == "fixed-upload" and contents:
            return uploaded_fixed_source_info(contents, filename)
        raise PreventUpdate

    @app.callback(
        Output("fixed-slice-slider", "max"),
        Output("fixed-slice-slider", "value"),
        Output("fixed-slice-slider", "marks"),
        Output("fixed-slice-slider", "disabled"),
        Output("fixed-source-status", "children"),
        Input("fixed-source-store", "data"),
    )
    def update_fixed_slider(
        source_info: SourceInfo,
    ) -> tuple[int, int, dict[int, str], bool, str]:
        """Update the slice slider for the active fixed source.

        Parameters:
            source_info: Metadata for the active fixed source.

        Returns:
            Slider maximum, value, marks, disabled flag, and status text.
        """
        depth = int(source_info["depth"])
        slice_index = int(source_info["slice_index"])
        shape = source_info["shape"]
        status = (
            f"Loaded {source_info['name']} with displayed shape "
            f"{shape[0]} x {shape[1]} and {depth} slice(s)."
        )
        return depth - 1, slice_index, slice_slider_marks(depth), depth <= 1, status

    @app.callback(
        Output("moving-source-store", "data"),
        Input("moving-upload", "contents"),
        Input("rotate-moving", "n_clicks"),
        Input("flip-moving", "n_clicks"),
        State("moving-upload", "filename"),
        State("moving-source-store", "data"),
        prevent_initial_call=True,
    )
    def update_moving_image(
        contents: str | None,
        rotate_clicks: int | None,
        flip_clicks: int | None,
        filename: str | None,
        moving_source_info: SourceInfo,
    ) -> SourceInfo:
        """Update the PC3 source after upload or transforms.

        Parameters:
            contents: Uploaded image data URI.
            rotate_clicks: Number of moving-image rotation button clicks.
            flip_clicks: Number of moving-image horizontal flip button clicks.
            filename: Uploaded filename.
            moving_source_info: Metadata for the active PC3 source.

        Returns:
            Metadata for the updated PC3 source.
        """
        if ctx.triggered_id == "rotate-moving":
            if not rotate_clicks:
                raise PreventUpdate
            return transformed_moving_source_info(moving_source_info, "rotate")
        if ctx.triggered_id == "flip-moving":
            if not flip_clicks:
                raise PreventUpdate
            return transformed_moving_source_info(moving_source_info, "flip")
        if ctx.triggered_id == "moving-upload" and contents:
            return uploaded_moving_source_info(contents, filename)
        raise PreventUpdate

    @app.callback(
        Output("fixed-points-store", "data"),
        Input("fixed-graph", "clickData"),
        Input("undo-fixed", "n_clicks"),
        Input("reset-points", "n_clicks"),
        Input("fixed-slice-slider", "value"),
        Input("rotate-fixed", "n_clicks"),
        Input("rotate-moving", "n_clicks"),
        Input("flip-fixed", "n_clicks"),
        Input("flip-moving", "n_clicks"),
        State("fixed-points-store", "data"),
        prevent_initial_call=True,
    )
    def update_fixed_points(
        click_data: dict[str, Any] | None,
        undo_clicks: int | None,
        reset_clicks: int | None,
        slice_index: int | None,
        fixed_rotate_clicks: int | None,
        moving_rotate_clicks: int | None,
        fixed_flip_clicks: int | None,
        moving_flip_clicks: int | None,
        points: list[Point] | None,
    ) -> list[Point]:
        """Update fixed-image landmarks from clicks and controls.

        Parameters:
            click_data: Fixed graph click payload.
            undo_clicks: Number of fixed undo button clicks.
            reset_clicks: Number of reset button clicks.
            slice_index: Active fixed-volume slice index.
            fixed_rotate_clicks: Number of fixed-image rotation button clicks.
            moving_rotate_clicks: Number of moving-image rotation button clicks.
            fixed_flip_clicks: Number of fixed-image horizontal flip button clicks.
            moving_flip_clicks: Number of moving-image horizontal flip button clicks.
            points: Current fixed landmark list.

        Returns:
            Updated fixed landmark list.
        """
        triggered_id = ctx.triggered_id
        if triggered_id in {
            "reset-points",
            "fixed-slice-slider",
            "rotate-fixed",
            "rotate-moving",
            "flip-fixed",
            "flip-moving",
        }:
            return []
        if triggered_id == "undo-fixed":
            return undo_last_point(points)
        if triggered_id == "fixed-graph":
            return append_clicked_point(click_data, points)
        raise PreventUpdate

    @app.callback(
        Output("moving-points-store", "data"),
        Input("moving-graph", "clickData"),
        Input("undo-moving", "n_clicks"),
        Input("reset-points", "n_clicks"),
        Input("fixed-slice-slider", "value"),
        Input("rotate-fixed", "n_clicks"),
        Input("rotate-moving", "n_clicks"),
        Input("flip-fixed", "n_clicks"),
        Input("flip-moving", "n_clicks"),
        State("moving-points-store", "data"),
        prevent_initial_call=True,
    )
    def update_moving_points(
        click_data: dict[str, Any] | None,
        undo_clicks: int | None,
        reset_clicks: int | None,
        slice_index: int | None,
        fixed_rotate_clicks: int | None,
        moving_rotate_clicks: int | None,
        fixed_flip_clicks: int | None,
        moving_flip_clicks: int | None,
        points: list[Point] | None,
    ) -> list[Point]:
        """Update moving-image landmarks from clicks and controls.

        Parameters:
            click_data: Moving graph click payload.
            undo_clicks: Number of moving undo button clicks.
            reset_clicks: Number of reset button clicks.
            slice_index: Active fixed-volume slice index.
            fixed_rotate_clicks: Number of fixed-image rotation button clicks.
            moving_rotate_clicks: Number of moving-image rotation button clicks.
            fixed_flip_clicks: Number of fixed-image horizontal flip button clicks.
            moving_flip_clicks: Number of moving-image horizontal flip button clicks.
            points: Current moving landmark list.

        Returns:
            Updated moving landmark list.
        """
        triggered_id = ctx.triggered_id
        if triggered_id in {
            "reset-points",
            "fixed-slice-slider",
            "rotate-fixed",
            "rotate-moving",
            "flip-fixed",
            "flip-moving",
        }:
            return []
        if triggered_id == "undo-moving":
            return undo_last_point(points)
        if triggered_id == "moving-graph":
            return append_clicked_point(click_data, points)
        raise PreventUpdate

    @app.callback(
        Output("fixed-graph", "figure"),
        Output("moving-graph", "figure"),
        Output("points-summary", "children"),
        Input("fixed-source-store", "data"),
        Input("fixed-slice-slider", "value"),
        Input("moving-source-store", "data"),
        Input("fixed-points-store", "data"),
        Input("moving-points-store", "data"),
    )
    def refresh_display(
        fixed_source_info: SourceInfo,
        slice_index: int | None,
        moving_source_info: SourceInfo,
        fixed_points: list[Point] | None,
        moving_points: list[Point] | None,
    ) -> tuple[go.Figure, go.Figure, list[Any]]:
        """Refresh image figures and the landmark-pair summary.

        Parameters:
            fixed_source_info: Metadata for the active fixed source.
            slice_index: Active fixed-volume slice index.
            moving_source_info: Metadata for the active PC3 source.
            fixed_points: Current fixed-image landmarks.
            moving_points: Current moving-image landmarks.

        Returns:
            Fixed figure, moving figure, and summary children.
        """
        fixed_image = fixed_slice_image(fixed_source_info, slice_index)
        moving_image = moving_source_display_image(moving_source_info)
        fixed_list = list(fixed_points or [])
        moving_list = list(moving_points or [])
        fixed_title = f"MRI {fixed_source_info['name']} slice {int(slice_index or 0)}"
        return (
            image_figure(fixed_image, fixed_list, fixed_title),
            image_figure(moving_image, moving_list, "PC3: img2"),
            points_summary(fixed_list, moving_list),
        )

    @app.callback(
        Output("registered-graph", "figure"),
        Output("overlay-graph", "figure"),
        Output("registration-status", "children"),
        Output("registered-result-store", "data"),
        Input("run-registration", "n_clicks"),
        State("fixed-source-store", "data"),
        State("fixed-slice-slider", "value"),
        State("moving-source-store", "data"),
        State("fixed-points-store", "data"),
        State("moving-points-store", "data"),
        State("stabilize-edges", "value"),
        prevent_initial_call=True,
    )
    def run_registration(
        run_clicks: int | None,
        fixed_source_info: SourceInfo,
        slice_index: int | None,
        moving_source_info: SourceInfo,
        fixed_points: list[Point] | None,
        moving_points: list[Point] | None,
        stabilize_values: list[str] | None,
    ) -> tuple[go.Figure, go.Figure, str, SourceInfo | None]:
        """Run non-rigid registration and update result figures.

        Parameters:
            run_clicks: Number of registration button clicks.
            fixed_source_info: Metadata for the active fixed source.
            slice_index: Active fixed-volume slice index.
            moving_source_info: Metadata for the active PC3 source.
            fixed_points: Current fixed-image landmarks.
            moving_points: Current moving-image landmarks.
            stabilize_values: Checklist values controlling edge stabilization.

        Returns:
            Registered-image figure, overlay figure, status message, and result metadata.
        """
        if not run_clicks:
            raise PreventUpdate

        fixed_list = list(fixed_points or [])
        moving_list = list(moving_points or [])
        if len(fixed_list) != len(moving_list):
            message = (
                "Registration needs the same number of MRI and PC3 landmarks. "
                f"Current counts are {len(fixed_list)} and {len(moving_list)}."
            )
            return (
                empty_figure("Registered PC3 in MRI space", message),
                empty_figure("MRI/registered PC3 overlay", message),
                message,
                None,
            )

        if len(fixed_list) < 3:
            message = "Select at least 3 matching landmark pairs before registration."
            return (
                empty_figure("Registered PC3 in MRI space", message),
                empty_figure("MRI/registered PC3 overlay", message),
                message,
                None,
            )

        fixed_image = fixed_slice_image(fixed_source_info, slice_index)
        moving_image = cached_image(str(moving_source_info["key"]))
        stabilize_edges = "stabilize" in (stabilize_values or [])
        try:
            if moving_source_info["kind"] == "scalar":
                registered_scalar = warp_scalar_moving_to_fixed(
                    moving_image=moving_image,
                    fixed_shape=fixed_image.shape[:2],
                    fixed_points=fixed_list,
                    moving_points=moving_list,
                    stabilize_edges=stabilize_edges,
                )
                registered = scalar_to_red_blue_rgb(registered_scalar)
            else:
                registered = warp_moving_to_fixed(
                    moving_image=moving_image.astype(np.uint8),
                    fixed_shape=fixed_image.shape[:2],
                    fixed_points=fixed_list,
                    moving_points=moving_list,
                    stabilize_edges=stabilize_edges,
                )
                registered_scalar = array_to_scalar_image(registered)
        except Exception as error:
            message = f"Registration failed: {error}"
            return (
                empty_figure("Registered PC3 in MRI space", message),
                empty_figure("MRI/registered PC3 overlay", message),
                message,
                None,
            )

        overlay = blend_images(fixed_image, registered)
        message = (
            f"Registration complete using {len(fixed_list)} landmark pair(s). "
            "The registered PC3 image has the same pixel space as the selected MRI slice."
        )
        return (
            image_figure(registered, [], "Registered PC3 in MRI space"),
            image_figure(overlay, fixed_list, "MRI/registered PC3 overlay"),
            message,
            make_moving_source_info(registered_scalar, "registered PC3", "scalar"),
        )

    @app.callback(
        Output("save-status", "children"),
        Input("save-registered", "n_clicks"),
        State("registered-result-store", "data"),
        State("fixed-source-store", "data"),
        State("fixed-slice-slider", "value"),
        prevent_initial_call=True,
    )
    def save_registered_result(
        save_clicks: int | None,
        registered_result_info: SourceInfo | None,
        fixed_source_info: SourceInfo,
        slice_index: int | None,
    ) -> str:
        """Save the latest registered PC3 slice as a spatial NIfTI.

        Parameters:
            save_clicks: Number of save button clicks.
            registered_result_info: Metadata for the latest registered scalar PC3.
            fixed_source_info: Metadata for the active MRI source.
            slice_index: MRI slice index used for the filename and affine.

        Returns:
            Status message with the output path.
        """
        if not save_clicks:
            raise PreventUpdate
        if not registered_result_info:
            return "Run registration before saving a result."

        registered_scalar = cached_image(str(registered_result_info["key"]))
        try:
            output_path = save_registered_nifti_slice(
                scalar_image=registered_scalar,
                fixed_source_info=fixed_source_info,
                slice_index=slice_index,
            )
        except ValueError:
            display_image = scalar_to_red_blue_rgb(registered_scalar)
            output_path = save_registered_image(display_image, slice_index)
            return (
                "MRI affine metadata was not available, so saved a PNG instead: "
                f"{output_path}."
            )

        return f"Saved registered PC3 2D NIfTI slice to {output_path}."


def create_app() -> Dash:
    """Create and configure the Dash application.

    Parameters:
        None.

    Returns:
        Configured Dash app instance.
    """
    app = Dash(__name__)
    app.title = "Non-Rigid Image Registration"
    app.layout = app_layout
    register_callbacks(app)
    return app


dash_app = create_app()
server = dash_app.server


if __name__ == "__main__":
    dash_app.run(debug=True)
